### ISSUE TITLE
pip install -r requirements.txt fail with conflicts

### ISSUE THREAD

**Issue by eliaweiss** [KarolynW/GPT-4-Snake-AI#1]
Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: pip is looking at multiple versions of joblib to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of cloudpickle to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of ale-py to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 24), ale-py==0.8.1, gym==0.21.0, gym[atari,classic-control]==0.11.0, gym[atari,classic-control]==0.12.0, gym[atari,classic-control]==0.12.1, gym[atari,classic-control]==0.12.4, gym[atari,classic-control]==0.12.5, gym[atari,classic-control]==0.12.6, gym[atari,classic-control]==0.13.0, gym[atari,classic-control]==0.13.1, gym[atari,classic-control]==0.14.0, gym[atari,classic-control]==0.15.3, gym[atari,classic-control]==0.15.4, gym[atari,classic-control]==0.15.6, gym[atari,classic-control]==0.15.7, gym[atari,classic-control]==0.16.0, gym[atari,classic-control]==0.17.0, gym[atari,classic-control]==0.17.1, gym[atari,classic-control]==0.17.2, gym[atari,classic-control]==0.17.3, gym[atari,classic-control]==0.18.0, gym[atari,classic-control]==0.18.3, gym[atari,classic-control]==0.19.0, gym[atari,classic-control]==0.20.0, gym[atari,classic-control]==0.21.0, gym[atari,classic-control]==0.22.0, gym[atari,classic-control]==0.23.0, gym[atari,classic-control]==0.23.1, gym[atari,classic-control]==0.24.0, gym[atari,classic-control]==0.24.1, gym[atari,classic-control]==0.25.0, gym[atari,classic-control]==0.25.1, gym[atari,classic-control]==0.25.2, gym[atari,classic-control]==0.26.0, gym[atari,classic-control]==0.26.1 and gym[atari,classic-control]==0.26.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.26.2 depends on gym 0.26.2 (from https://files.pythonhosted.org/packages/ab/b1/eb05a423eb801ab7d0715d6a3b28d92589e30b437052553df19ca2087240/gym-0.26.2.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.6))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.26.1 depends on gym 0.26.1 (from https://files.pythonhosted.org/packages/f1/67/ca925439eec51e1e6b5dab6c7412c367b7d9bc5c6c3fa9c8968146d80b8b/gym-0.26.1.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.6))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.26.0 depends on gym 0.26.0 (from https://files.pythonhosted.org/packages/65/75/145c54fdbfa90d440b76b892be2a1922caec759aecd3aa0b66e39caf53ca/gym-0.26.0.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.6))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.25.2 depends on gym 0.25.2 (from https://files.pythonhosted.org/packages/1c/5c/e5c14f3474e91038a51ec794350c7af9635a2faf3873c85989bf9dd127ce/gym-0.25.2.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.6))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.25.1 depends on gym 0.25.1 (from https://files.pythonhosted.org/packages/d2/2e/abef8d86e27e426bf74e5f6d044332bd67ebd956f9aad7fe2a6b871bd098/gym-0.25.1.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.6))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.25.0 depends on gym 0.25.0 (from https://files.pythonhosted.org/packages/97/9d/f9efa0fb93b67ee629240efe0863114697f9d6e9c7f22174645a348a4c66/gym-0.25.0.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.6))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.24.1 depends on gym 0.24.1 (from https://files.pythonhosted.org/packages/b8/0f/a56357a6228d93c8caa36c57f570419bdee433b9cdc644d94962ee6e2e5c/gym-0.24.1.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.6))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.24.0 depends on gym 0.24.0 (from https://files.pythonhosted.org/packages/34/e8/c8953e7fb2e3b3a232a21f87248b87fe9354b8db74e79ece99f53ce31a3d/gym-0.24.0.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.6))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.23.1 depends on gym 0.23.1 (from https://files.pythonhosted.org/packages/87/86/3f5467531428b6ce6f3c12d3121b4304d2ea1536a50775a4df036add37b8/gym-0.23.1.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.7))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.23.0 depends on gym 0.23.0 (from https://files.pythonhosted.org/packages/66/17/b4ec403562c0e8c56f1ce095dcf6d65b7faeabff87f46b6097ab45e6001a/gym-0.23.0.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.7))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.22.0 depends on gym 0.22.0 (from https://files.pythonhosted.org/packages/01/ef/09b53c076943c3722bac91a274825ece90985c1b3686d8426608fd741e30/gym-0.22.0.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.7))
    The user requested ale-py==0.8.1
    gym[atari,classic-control] 0.21.0 depends on ale-py~=0.7.1
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.20.0 depends on gym 0.20.0 (from https://files.pythonhosted.org/packages/f1/16/a421155206e7dc41b3a79d4e9311287b88c20140d567182839775088e9ad/gym-0.20.0.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.6))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.19.0 depends on gym 0.19.0 (from https://files.pythonhosted.org/packages/af/f5/958aa7f6f5b685896dbddf7436d06755bf23b12c65889b156566dd06c514/gym-0.19.0.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.6))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.18.3 depends on gym 0.18.3 (from https://files.pythonhosted.org/packages/1a/db/816fd52c0c196b6799e89d1f65b6c74fead2707cf7d447f3f354edfa7a44/gym-0.18.3.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.6))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.18.0 depends on gym 0.18.0 (from https://files.pythonhosted.org/packages/26/f2/e7ee20bf02b2d02263becba1c5ec4203fef7cfbd57759e040e51307173f4/gym-0.18.0.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.6))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.17.3 depends on gym 0.17.3 (from https://files.pythonhosted.org/packages/10/b0/8482162d2fab1c805f83ce0ba953e5970691917f196fef62b93ed7cc14a2/gym-0.17.3.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.5))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.17.2 depends on gym 0.17.2 (from https://files.pythonhosted.org/packages/b3/99/7cc3e510678119cdac91f33fb9235b98448f09a6bdf0cafea2b108d9ce51/gym-0.17.2.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.5))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.17.1 depends on gym 0.17.1 (from https://files.pythonhosted.org/packages/77/48/c43b8a72b916cc70896aa431b0fc00d1481ae34e28dc55e2144f4c77916b/gym-0.17.1.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.5))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.17.0 depends on gym 0.17.0 (from https://files.pythonhosted.org/packages/d6/81/2924b60e2befc192c7e43279ff388c68104515228b865506f13b4f18c338/gym-0.17.0.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=3.5))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.16.0 depends on gym 0.16.0 (from https://files.pythonhosted.org/packages/14/d3/d683fb120771489ae0a49bbaf6085942751c039f5f5e02e9775b7883c377/gym-0.16.0.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.15.7 depends on gym 0.15.7 (from https://files.pythonhosted.org/packages/e0/01/8771e8f914a627022296dab694092a11a7d417b6c8364f0a44a8debca734/gym-0.15.7.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.15.6 depends on gym 0.15.6 (from https://files.pythonhosted.org/packages/da/10/f205495ff7fa324c1f5d3e6c7d056fa0e50c27e319c5533bba14bc2e75c2/gym-0.15.6.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.15.4 depends on gym 0.15.4 (from https://files.pythonhosted.org/packages/1d/85/a7a462d7796f097027d60f9a62b4e17a0a94dcf12ac2a9f9a913333b11a6/gym-0.15.4.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.15.3 depends on gym 0.15.3 (from https://files.pythonhosted.org/packages/d2/88/a7186ffe1f33570ad3b8cd635996e5a3e3e155736e180ae6a2ad5e826a60/gym-0.15.3.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.14.0 depends on gym 0.14.0 (from https://files.pythonhosted.org/packages/61/75/9e841bc2bc75128e0b65c3d5255d0bd16becb9d8f7120b965d41b8e70041/gym-0.14.0.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.13.1 depends on gym 0.13.1 (from https://files.pythonhosted.org/packages/9d/38/87aefd5388f6062267384b7e8f97dbc27c54b3e6137a5148b43d5c10890c/gym-0.13.1.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.13.0 depends on gym 0.13.0 (from https://files.pythonhosted.org/packages/8a/2d/d4ad0ef5159e87d66339f1dfaa4736687bf2699c3b8ce9e57998f28bb5a1/gym-0.13.0.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.12.6 depends on gym 0.12.6 (from https://files.pythonhosted.org/packages/0d/3d/cb5420c58c8b475e8a70fdf0c949602908381196f164dac8caf46bb4f2fb/gym-0.12.6.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.12.5 depends on gym 0.12.5 (from https://files.pythonhosted.org/packages/0c/c4/307107c687f75267d645415d57db8c0a6e29e20ac30d8f4a10e8030b6737/gym-0.12.5.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.12.4 depends on gym 0.12.4 (from https://files.pythonhosted.org/packages/8f/1f/edf9611bc202069790e4d43a3bb70550fc1a9b22649b8666efe41b3601ec/gym-0.12.4.tar.gz (from https://pypi.org/simple/gym/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.12.1 depends on gym 0.12.1 (from https://files.pythonhosted.org/packages/7b/57/e2fc4123ff2b4e3d61ae9b3d08c6878aecf2d5ec69b585ed53bc2400607f/gym-0.12.1.tar.gz (from https://pypi.org/simple/gym/))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.12.0 depends on gym 0.12.0 (from https://files.pythonhosted.org/packages/c7/98/fad8b85827d9aca922eec6a8747dd696aac281ebdc4b1225acf51f8f612f/gym-0.12.0.tar.gz (from https://pypi.org/simple/gym/))
    The user requested gym==0.21.0
    stable-baselines3 1.7.0 depends on gym==0.21
    gym[atari,classic-control] 0.11.0 depends on gym 0.11.0 (from https://files.pythonhosted.org/packages/52/d6/d0b7918f4da95fbc64cf9466d45c7880b1d09cc5b46215aaad1d8e185297/gym-0.11.0.tar.gz (from https://pypi.org/simple/gym/))

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by KarolynW** [comment]
Easiest way to resolve is manual installation - I will fix the requirements text when I get a chance but just try the following:

Make sure you are using Python 3.7 (gym and pygame have issues with newer versions)

Pip install the packages manually listed in the script.

You may also need to make adjustments depending upon your system (I was using Windows).

**Comment by KarolynW** [comment]
Updated requirements.txt - should be fine now.
